services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis:6379
      GEOIP_DB_PATH: /app/data/GeoLite2-Country.mmdb
    volumes:
      - ./data/GeoLite2-Country.mmdb:/app/data/GeoLite2-Country.mmdb:ro
    depends_on:
      redis:
        condition: service_healthy
